s153
SpeciesConservationLandscapes/task_scl_eff_pot_hab pull request #8
Opened 2021-03-26 22:49 UTC by thanrobinson

Dynamic thresholding implemented

2021-03-26 22:51 UTC, thanrobinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [better thresholding choices for landscape creation](https://trello.com/c/4FffbdOI/153-better-thresholding-choices-for-landscape-creation)

2021-03-29 14:27 UTC, saanobhaai requested changes
Brilliant stuff! Much more readable and pythonic now. I've done an extra-careful review because of your interest and how good it is, but it's basically great as is.

Note in addition to the line comments that
`import time`
can be removed.

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +        "hii": 18,  # TODO: have a default value if thresholding functions fail
Not a `TODO` anymore, is it? just a comment about what it is?

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +        self.zones_image = ee.Image()
This isn't used anywhere... I think maybe you could remove the property below and write here just
`self.zone_image = self.zones.reduceToImage([self.ZONES_LABEL], ee.Reducer.first()).selfMask()`
(property would be more helpful/appropriate if there was something dynamic about what determines the output)

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +    def build_threshold_calc_image(
There are two ways to go for a method like this:
1. Make it work intrinsically with class properties, and remove args -- this is more obj-oriented, but less flexible. Could even make it a class property.
2. Make it entirely abstract, in which case it could even be outside the class (or more likely indicate that it's private be renaming something like `_threshold_calc_image`).
I like 2), in which case I would move lines 207-209 to `calc` so that `probability_image`, which in theory could be anything, does not then depend on an input-specific threshold.

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +                    "{}_all_vals".format(variable_name),
I like the python 3 string formatting syntax, e.g.
`f"{variable_name}_all_vals"`

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +        hii_thresholding_histograms = self.histogram_calc(
`build_threshold_calc_image` gives me a threshold image for whatever variable/probability combo I throw at it. In this case we're only doing HII, but we might decide to do others in the same way. Should the `histogram_reducer` then be renamed so it's specific to a) hii or b) the abstract kind of dynamic threshold reducing we're doing? iow if we wanted to do the same thing for another variable, would we use the same reducer, or would we add a slightly different one to that dict?

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +    def zone_threshold_image(self, zone_threshold_lists, variable_name):
This is awesome; succinct, I know instantly what it does, and consistent (like my comment about `build_threshold_calc_image` option 2 above)

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +        # Each zone_object  contains the counts and histograms for a zone
double space, but great comment... maybe add a line about what it returns?

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +            zone_dictionay = ee.Dictionary(zone_object)
var spelling

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +            # threshold_calcis mapped over hist_combine
spelling and spacing

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +            zone_number = zone_dictionay.get("zone")  # currently this does not get used
remove comment -- yes it does...

2021-03-29 14:27 UTC, saanobhaai commented on src/task_scl_eff_pot_hab.py
> +                return ee.Number(bin_value.multiply(difference.gte(0))).int()
A comment about this line and the next might be helpful... like what would our future selves need to do to enhance this key selection bit? Also -- do we need to protect against the possibility of `difference` never being gte 0?

2021-03-29 18:56 UTC, merged